
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: business_development
  username: root
  password: root
  pool: 5
  host: localhost
 
production:
  adapter: mysql
  database: business_production
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: business_test
  pool: 5
  host: localhost